apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-image
  labels:
    app: server-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-image
  template:
    metadata:
      labels:
        app: server-image
    spec:
      containers:
      - name: server-image
        image: wkawka/presentation:1.5
        ports:
        - containerPort: 1234
        env:
        - name: SERVER_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-password
        - name: SERVER_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-username
        - name: SERVER_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: server-image-service
spec:
  selector:
    app: server-image
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      nodePort: 31000
